### ISSUE TITLE
mixins are not applied properly

### ISSUE THREAD

**Issue by giang12** [ColonelBundy/moleculer-decorators#15]
---
name: mixins are not applied properly

---

## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior

FooService has action `foo`
![image](https://user-images.githubusercontent.com/5290460/55918360-aeb0d000-5ba7-11e9-88ea-6b0971117dfb.png)

MainService mixins[ServiceFoo]... so expecting `main.foo` to exist

## Current Behavior

not found
![image](https://user-images.githubusercontent.com/5290460/55918410-e15ac880-5ba7-11e9-9bc7-4c4fc90547e2.png)

### Reproduce code snippet
```js
//foo.service
'use strict';
const moleculer = require('moleculer');
const { Service, Action, Method, Event } = require('moleculer-decorators');

@Service({})
class foo extends moleculer.Service {
  // Optional constructor
  constructor(broker,s?) {
    super(broker,s);
  }

  @Action()
  foo() {
     return 'baz'; 
   }

   @Method
   foo2(){
     return 'baz2';
   }
}

module.exports = foo;
```
```js
//main.service
"use strict";

const moleculer = require('moleculer');
const { Service, Action, Event, Method } = require('moleculer-decorators');
const foo = require('./foo.service');

@Service({
  mixins: [foo],
  settings: {
  }
})
class main extends moleculer.Service {

  // Optional constructor
  constructor(broker, s) {
    super(broker, s)
    this.settings = { // Overrides above by default, to prevent this, add "constructOverride: false" to @Service
      foo: "mainbaz"
    }
  }

  // @Action({
  //   skipHandler: true // Any options will be merged with the mixin's action.
  // })
  // foo() { // this function will never be called since a mixin will override it, unless you specify skipHandler: false.

  // }

  // With options
  // No need for "handler:{}" here
  @Action()
  yo(ctx) {
    return "yo"
  }

}


const broker = new moleculer.ServiceBroker({
  namespace: "test",
  logger: console,
  logLevel: "debug",
});
broker.createService(main);
broker.start();
broker.repl();
export {}
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.8
* Moleculer-decorators": 1.0.22
* NodeJS version: 10
* Operating System: centos

### Failure Logs
```

```

**Comment by davidfrtala** [comment]
Submitted a PR fixing this issue. Waiting for @ColonelBundy to review, merge & publish

**Comment by ColonelBundy** [comment]
Good cathc!

Fixed in #16 by @davidfrtala 

Thank you!

**Comment by giang12** [comment]
noted the issue still exists. Heres the test repo https://github.com/giang12/moldecormixinsbug

**Comment by tobydeh** [comment]
any update on this?
